# Generated by Django 3.0.8 on 2020-07-14 16:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('PalikaType', models.CharField(max_length=100)),
                ('PalikaName', models.CharField(max_length=100)),
                ('Ward_No', models.CharField(max_length=100)),
                ('Ward_Office_Address', models.CharField(max_length=100)),
                ('Ward_Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('X_Cords', models.FloatField()),
                ('Y_Cords', models.FloatField()),
                ('Chairperson_Name', models.CharField(max_length=100)),
                ('Chaiperson_Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Secretary_Name', models.CharField(max_length=100)),
                ('Secretary_Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Area', models.FloatField(max_length=100)),
                ('Total_Households', models.IntegerField()),
                ('Total_Population', models.IntegerField()),
                ('Total_Male_Population', models.IntegerField()),
                ('Total_Female_Population', models.IntegerField()),
                ('Website', models.URLField()),
                ('Email', models.EmailField(max_length=254)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enteredArea', models.CharField(max_length=100)),
                ('enteredChaiPersonContact', models.CharField(max_length=100)),
                ('enteredChairPersonName', models.CharField(max_length=100)),
                ('enteredEmail', models.CharField(max_length=100)),
                ('enteredFemalePop', models.CharField(max_length=100)),
                ('enteredHouseholds', models.CharField(max_length=100)),
                ('enteredMalePop', models.CharField(max_length=100)),
                ('enteredPalikaName', models.CharField(max_length=100)),
                ('enteredSecretaryContact', models.CharField(max_length=100)),
                ('enteredSecretaryName', models.CharField(max_length=100)),
                ('enteredTotalPop', models.CharField(max_length=100)),
                ('enteredWardContactNo', models.CharField(max_length=100)),
                ('enteredWardNo', models.CharField(max_length=100)),
                ('enteredWardOfficeAddress', models.CharField(max_length=100)),
                ('enteredWebsite', models.CharField(max_length=100)),
                ('enteredXCords', models.CharField(max_length=100)),
                ('enteredYCords', models.CharField(max_length=100)),
                ('selectedDistrict', models.CharField(max_length=100)),
                ('selectedPalikaType', models.CharField(max_length=100)),
                ('selectedPro', models.CharField(max_length=100)),
            ],
        ),
    ]
